
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "8080:8080"
    expose:
      - "49152-65535:49152-65535"


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
